//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sportzly.Web.Controls {
    
    
    public partial class ActivitiesControl {
        
        /// <summary>
        /// LightBoxControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sportzly.Web.Controls.LightBoxControl LightBoxControl;
        
        /// <summary>
        /// CheersJeers1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sportzly.Web.Controls.CheersJeers CheersJeers1;
        
        /// <summary>
        /// Comments1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sportzly.Web.Controls.CommentsControl Comments1;
    }
}
