//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sportzly.Web.Controls {
    
    
    public partial class MyActivitiesControl {
        
        /// <summary>
        /// LightBoxControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sportzly.Web.Controls.LightBoxControl LightBoxControl;
        
        /// <summary>
        /// MyCheersJeers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sportzly.Web.Controls.MyCheersJeers MyCheersJeers;
        
        /// <summary>
        /// MyCommentsControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sportzly.Web.Controls.MyCommentsControl MyCommentsControl;
    }
}
